site_name: TI Documentation
site_description: Documentación TI - SilHer Corp.
site_author: José Castro

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy

  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro

    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Inicio: index.md

  - SIGNIA:
      - Baja de Sistemas: signia/baja-sistemas.md

  - HREPS:
      - Cuadre de Facturas: hreps/cuadre-facturas.md

  - KURA:
      - Facturas Estado 1: kura/facturas-estado-1.md

plugins:
  - search
